name: release validation

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  validate:
    uses: MCEnvision/.github/.github/workflows/release-validation.yml@853407d48c17309e2024e594e49d6dda266ac26d
    with:
      shared-ref: "853407d48c17309e2024e594e49d6dda266ac26d"
